# Exported from Render on 2025-12-17T05:56:14Z
version: '1'
projects:
    - name: Zaakiyah
      environments:
          - name: Production
            services:
                - type: web
                  name: zaakiyah-frontend
                  runtime: static
                  repo: https://github.com/Zaakiyah/zaakiyah-frontend
                  envVars:
                      - key: VITE_FIREBASE_VAPID_KEY
                        sync: false
                      - key: VITE_MEASUREMENT_ID
                        sync: false
                      - key: VITE_FIREBASE_APP_ID
                        sync: false
                      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
                        sync: false
                      - key: VITE_FIREBASE_STORAGE_BUCKET
                        sync: false
                      - key: VITE_FIREBASE_PROJECT_ID
                        sync: false
                      - key: VITE_FIREBASE_AUTH_DOMAIN
                        sync: false
                      - key: VITE_FIREBASE_API_KEY
                        sync: false
                      - key: VITE_WEBSITE_URL
                        sync: false
                      - key: VITE_API_URL
                        sync: false
                  buildCommand: pnpm install --frozen-lockfile; pnpm run build
                  staticPublishPath: dist
                  autoDeployTrigger: commit
                  routes:
                      - type: rewrite
                        source: /*
                        destination: /index.html
